config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'posts#index'
  resources :users 
  resources :friendships
  resources :posts do
    resources :comments
  end 

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user  
    def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"] || session["devise.linkedin_data"] && session["devise.linkedin_data"]["extra"]["raw_info"] || session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.birthday = data["user_birthday"] if user.birthday.blank?
        user.first_name = data["first_name"] if user.first_name.blank?
        user.last_name = data["last_name"] if user.last_name.blank?
        user.image = data["picture"] if user.last_name.blank?
      end
    end
    end
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: %i[facebook linkedin github]
  has_many :posts
  has_many :comments, through: :posts
  
  #For Paperclip
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  
  #For omniauth
  
  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.username = auth.info.name 
    user.birthday = auth.info.birthday
    user.first_name = auth.info.first_name
    user.last_name = auth.info.first_name
    user.image = auth.info.picture
    # assuming the user model has a name
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    # user.skip_confirmation!
  end
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def linkedin
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Linkedin") if is_navigational_format?
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end


  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div class="container" style="margin-top: 10%">
<% @users.each do |user| %>
<br>
<%= link_to user.username, user %>
<%= user.email %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container" style="float:right; margin-top: 5%; text-align: left;">
<div class="card" style="width: 45rem;">
  <% if @user.image.file? %>
  <%= image_tag @user.image.url, :class => "img-fluid" %>
  <% else %>
  <%= image_tag 'missing.png', :size => "718x403" %>
  <% end %>
  <div class="card-body">
    <h5 class="card-title"><strong><%= @user.username %></strong></h5>
    <%= link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post %>
    <p class="card-text"><%= @user.about %></p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Name: <% @user.first_name %> <%= @user.last_name %></li>
    <li class="list-group-item">Birthday: <%= @user.birthday %></li>
    <li class="list-group-item">Location: <%= @user.location %></li>
    <li class="list-group-item">Email: <%= mail_to @user.email %></li>
  </ul>
<div style="background-color: white;">
  <hr>
    <h4><strong>Friends</strong></h4>
<ul>
  <% for friendship in @user.friendships %>
    <li>
      <%=h friendship.friend.username %>
      <!-- Allow only owner of user profile to remove their own friends -->
        <% if @user == current_user %>
      (<%= link_to "remove", friendship, :method => :delete %>)
        <% end %>
    </li>
  <% end %>
</ul>

<h4><Strong>Friended by Users</strong></h4>
<ul>
  <% for user in @user.inverse_friends %>
    <li><%=h user.username %></li>
  <% end %>
</ul>
</div>  
</div>
</div>