config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'posts#index'
  resources :users 
  resources :friendships
  resources :posts do
    resources :comments
  end 

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @post = Post.where(["title LIKE ?","%#{params[:search]}%"]).paginate(page: params[:page], per_page: 9)
    end 
    
    def show
        @post = Post.find(params[:id])
    end
    
    def new
    if user_signed_in?
        @post = current_user.posts.build
    else
        redirect_to '/users/sign_in'
    end 
    end 
    
    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to @post
        else 
            render 'new'
        end 
    end 
    
    def edit 
        @post = Post.find(params[:id])
    end 
    
    def update
    @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to @post
        else 
            render 'edit'
        end  
    end 
    
    def destroy
         @post = Post.find(params[:id])
         @post.destroy
         
         redirect_to posts_path
    end 
    
    private 
        def post_params
            params.require(:post).permit(:title, :body)
        end 
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="container" style="margin: 10%;">
<div class="new-post">
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    
    <p>
    <%= f.submit %>
    </p>
<% end %>
</div>
</div>

app/views/posts/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta name="generator" content=
  "HTML Tidy for Linux (vers 25 March 2009), see www.w3.org" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <title></title>
</head>

<body>
  <!-- Welcome Page -->
  <% if !user_signed_in? %>
  <div class="container" style="margin-top: 5%; display: block; margin-left: auto; margin-right: auto; width: 40%;">
    <div class="row">
      <div class="col-xs-12">
        <%= image_tag("logo.png", :alt => "logo") %>
      </div>
    </div>
  </div>
  <div class="container" style="margin-top: 1%; background-color: white; color: red; border-style: solid; border-color: black;">
    <div class="row">
      <div class="col-xs-12" style="font-family: Verdana;">
        <h1>
          <i>
            "Welcome to Project Finder!</br> 
            Where all your projects come to life."</br>
            Have you ever wanted to form a team? Stress no more!
          </i>
        </h1>
      </div>
    </div>
  </div>
  <% end %>
  
  <!--CARDS SECTION -->
  <% if !user_signed_in? %>
  <div class="album py-5 bg-light" style="margin-top: 1%">
  <% end %>
  <% if user_signed_in? %>
  <div class="album py-5 bg-light" style="margin-top: 3%">
  <% end %>
    <div class="container">
      <div class="row">
        <% @post.each do |post| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow" style="border-color: black; background-color: lightblue;">
            <div class="card-body">
              <h5 class="card-title" style="font-family: Verdana;"><strong><%= link_to post.title, post %></strong></h5>
              <p class="card-text" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis;"><i><%= post.body %></i></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to "View", post_path(post), :class => 'btn btn-sm btn-outline-secondary' %> 
                </div>
                <small class="text-muted">Created <%= time_ago_in_words(post.created_at) %></small>
              </div>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <!-- BEGIN PAGINATION TOOL -->
          <%= will_paginate @post, previous_label: "Previous Page<<", next_label: ">>Next Page", inner_window: 1, outer_window: 0 %>
      <!-- END PAGIATION TOOL -->
    </div>
  </div>
<!--END OF CARDS SECTION-->

<!-- FOOTER SECTION -->
  <footer class="footer">
    <div class="container text-center">
      <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
      <a href="https://www.twitter.com/"><i class="fa fa-twitter"></i></a>
      <a href="https://www.linkedin.com/"><i class="fa fa-linkedin"></i></a>
      <a href="https://www.google.com/"><i class="fa fa-google-plus"></i></a>
      <a href="https://www.skype.com/"><i class="fa fa-skype"></i></a>
      <a href="https://www.instagram.com/"><i class="fa fa-instagram"></i></a>
    </div>
    <div class="container text-center">
      <p class="footer__copyright"><i class="icon icon_logo"></i> &copy; 2018 Project Finder Ltd  <span class="all-rights-reserved">&ndash; All rights reserved</span></p>
    </div>
  </footer>
  <!-- END OF FOOTER SECTION -->
  
</body>

</html>

 
  

app/views/posts/new.html.erb
<div class="new_post_container">
<div class="new-post">
<div class="container" style="color: white">
<h1>New Post</h1>
</div>
<%= form_for :post, url: posts_path do |f| %>
    <p>
        <%= f.label :title %><br>
        <%= f.text_field(:title, {:class => 'form-control'}) %>
    </p>

    <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
    </p>
    
    <p>
    <%= f.submit %>
    </p>
<% end %>
</div>
</div>

app/views/posts/show.html.erb
<div class="container" style="margin-top: 6%; border-radius: 25px; border: 2px solid #1b1e2182; margin-top: 6%; font-family: Lucida Console; background-color: lightblue; padding-bottom: 5px; padding-top: 5px;">
<h1 class="title"><%= @post.title %></h1> 
    
<hr>

<p class="date"> Submitted <%= time_ago_in_words(@post.created_at) %> Ago by
<!-- Checks if a user even exist for this post -->
<% if defined? (@post.user.username) %> 
user: 
<a href="https://groupfinder-mileswinston23.c9users.io/users/<%= @post.user.id %>"><%= @post.user.username %></a>
    </p>
<% end %>
<p class="body">
<%= @post.body %></p>

<% if @post.user == current_user %>
<%= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-sm btn-outline-secondary' %>
<%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, :class => 'btn btn-sm btn-outline-secondary' %>
<% end %>

<hr>

<h3 style="padding-bottom: 20px;">Comments</h3>
<% @post.comments.each do |comment| %>
    <div class="card" style="margin-bottom: 2%">
    <div class="card-header">
    <h4><!-- Checks if a user exist for this post -->
        <% if defined? (@post.user.username) %> 
        <a href="https://groupfinder-mileswinston23.c9users.io/users/<%= comment.user_id %>"><%= comment.username %></a>
        <% end %>
        <span class="text-muted"> commented <%= time_ago_in_words(comment.created_at) %> ago</span>
    </h4>
    <p class="card-text"><%= comment.body %></p>
    <!--<a href="https://groupfinder-mileswinston23.c9users.io/users/<%= comment.user_id %>" class="card-link">View Profile</a> -->
    <!-- Check to see if the current user is signed in. If so, delete and edit will be shown as options -->
    <% if user_signed_in? && comment.user_id == current_user.id %>
    <a><%= link_to 'Delete',  post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' }, :class => "card-link;",:style => "margin-left: 20px;" %></a>
    <a><%= link_to 'Edit', edit_post_comment_path(comment.post, comment), :class => "card-link;",:style => "margin-left: 20px;" %></a>
    <% end %>
    </a>
  </div>
</div>
<% end %>

<hr>
<% if user_signed_in? %>
<h3> Add Comments </h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
  <%= f.label :username, :value => 'Posting as: '  + current_user.username %><br>
  <%= f.hidden_field :username, :value => current_user.username %>
  </p>
  <p>
   <%= f.label :body %><br>
   <%= f.text_area(:body, {:class => 'form-control', :required => true}) %>
  </p>
  <p>
     <%= f.submit({:class => 'btn btn-default'}) %>
  </p>
<% end %>
<% end %>
</div>